# Site settings
title: Your awesome title
email: andrespires[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Enthusiast of everything on the domains of family, swimming, 
  hockey underwater, tech innovations, entrepreneurship, 
  futurism, computer science, computer music and every source of 
  true knowledge and love. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrespires.github.io" # the base hostname & protocol for your site
twitter_username: _andrespires
github_username:  andrespires

# Build settings
markdown: kramdown
